### ISSUE TITLE
Revealing all players choices

### ISSUE THREAD

**Issue by saurabh2209** [LeadsOnDemand/planningPoker#1]
4. You need to reveal all players choices only after all players have selected an estimate. Can you elaborate a bit about this?

Also do i need to implement the entire game logic for the poker game?

**Comment by Jhorlin** [comment]
@saurabh2209 great question!
The state of the game would be.

1. You have an active game with more that two two player. For our example assume we have exactly two players. Lets call them player "a" and player "b".
2. When player "a" submits an answer you can do nothing or notify player "a" that you are still waiting on other players.
3. When player "b" submits an answer since all platers in the current game have submitted,  you can now reveal all players selected answers to each other.

The exercise above it not overly complicated, but it is not trivial either, this is common concurrency problem and would like to see how you attack this problem.

Feel free to implement as much as you can and we can discuss what you had trouble with. I would say even if you don't get this feature right, I would like to see an attempt.
